import Header from "@/components/Header";
import { Inter } from "next/font/google";
import "../index.css";
import Hero from "@/components/Hero";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center justify-center">
          <div className="content w-[100%] ">
            <Header />
            {children}
          </div>
        </main>{" "}
      </body>
    </html>
  );
}
